project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - talk.qmd

website:
  title: "Hondga Yuan"
  search: true
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Presentation"
        href: talk.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/hongda-yuan
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/TonyYuanMD/TonyYuanMD.github.io
          - text: Other Repos
            href:  https://github.com/TonyYuanMD?tab=repositories

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



