project:
  type: website
  output-dir: docs

website:
  title: "Hondga Yuan"
  background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - talks.qmd
      - about.qmd
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/hongda-yuan
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



