project:
  type: website
  output-dir: docs

website:
  title: "Hondga Yuan"
  background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - talks.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



