project:
  type: website
  output-dir: docs
  resources: 
    - files
  render:
    - index.qmd
    - talk.qmd
    - contact.qmd

website:
  google-analytics: "G-D79F5FH6KW"
  cookie-consent: True
  title: "Hondga Yuan"
  search: true
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Presentation"
        href: talk.qmd
      - text: "Contact"
        href: contact.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/hongda-yuan
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/TonyYuanMD/TonyYuanMD.github.io
          - text: Other Repos
            href:  https://github.com/TonyYuanMD?tab=repositories

format:
  html:
    theme: zephyer
    css: styles.css
    toc: true



